### PR TITLE
RH6: lsvmbus: Enable execute permission

### PR DESCRIPTION
**Pull request by santoshx**

### CODE REVIEW

**Comment by santoshx** [comment]
@johnsongeorge-w @prashantmhetar  Please review.

**Comment by johnsongeorge-w** [comment]
@santoshx This modification is for fixing which issue ?

**Comment by santoshx** [comment]
> @santoshx This modification is for fixing which issue ?

@johnsongeorge-w  On RH6, after I do ./rhel6-hv-driver-install we get following issue:

[root@localhost lis-next]# lsvmbus
-bash: /usr/sbin/lsvmbus: Permission denied

**Comment by johnsongeorge-w** [comment]
@santoshx Got it. Do the same modification for hv-rhel6 install script too.

**Comment by santoshx** [comment]
> @santoshx Got it. Do the same modification for hv-rhel7 install script too. Current bin has +x permission, still it would be good to do it in script.

@johnsongeorge-w Done

**Pull request merged**
