### PR TITLE
RH7: vmbus backport

### PR DESCRIPTION
**Pull request by prashantmhetar**

### CODE REVIEW

**Comment by prashantmhetar** [comment]
Verified with below tests with CentOS73 and 75:
1. Install/uninstall with reboot
2. Enable/disable the SRIOV 
3. Lisav2 verification test scripts like 
verify-ifup-nics.sh,  verify_vmbus_interrupts.sh, verify_vmbus_protocol_version.sh

**Comment by prashantmhetar** [comment]
closing this PR as adding dependent vmbus patch

**Comment by prashantmhetar** [comment]
Added backport RH7: vmbus: split ring buffer allocation from open
Tested these 3 backports with above test on centos 73/75 VM

**Comment by johnsongeorge-w** [comment]
Looks good.

**Pull request merged**
