### PR TITLE
RH6: hv_netvsc: Fix to remove slave sysfs link in netdev_upper_dev_un…

### PR DESCRIPTION
**Pull request by prashantmhetar**
…link

### CODE REVIEW

**Comment by prashantmhetar** [comment]
@santoshx please review this PR

**Comment by santoshx** [comment]
We'll not need this after we merge #642 
Let's hold this for a while to avoid merge conflict.

**Comment by santoshx** [comment]
@prashantmhetar 
Please close this. This is no longer needed.

**Comment by prashantmhetar** [comment]
Closing this PR

**Pull request closed without merging**
