### PR TITLE
RH6x: Fix a Network regression after ifdown.ifup

### PR DESCRIPTION
**Pull request by mboitei**
Network regression patch for RH6.

### CODE REVIEW

**Comment by santoshx** [comment]
As this is backport, please mention the commit id of original commit. So that it is to track.

**Comment by mboitei** [comment]
Please find the original commit. 

https://github.com/LIS/lis-next/commit/25c11bb2334036816cb94e643013ba314cbed4eb

**Comment by mboitei** [comment]
Changed the commit message,

**Comment by santoshx** [comment]
Ok from me.

**Pull request closed without merging**
