### PR TITLE
fixed compiling error in redhat6.7 using transparent sriov patch

### PR DESCRIPTION
**Pull request by stevecui**
fixed the compiling error in redhat6.7, and tested the patch in redhat6.7, 6.8, 6.10. They are all correct.

### CODE REVIEW

**Comment by prashantmhetar** [comment]
This patch resolves build issue specific to 6.7. Is this tested for lower versions < 6.7.
Do we need to have below patch for lower versions
https://github.com/prashantmhetar/lis-next/commit/43175e33d0b835b3238f6b73814ff0dc01a32a1e

**Comment by stevecui** [comment]
Only tested it in redhat6.7,6.8,6.9,6.10. Not test it from redhat6.0 to 6.6. Just now I reviewed Prashant's patch from redhat6.0 to 6.6. The next step need to merge this patch to Pashant's patch to support redhat6.7.

**Comment by stevecui** [comment]
For redhat6.7 bonding.h is not in /include/linux/, but in driver/net/bonding/ folder. To pass the compiling, the headers of bonding.h, bond_3ad.h, bond_alb.h, bond_options.h copy to lis-next/hv-rhel6.x/hv/ folder, and changed to hyperv_bonding.h, hyperv_bond_3ad.h, hyperv_bond_alb.h, hyperv_bond_options.h to support redhat6.7. And added macros to distinguish redhat6.7 and other distros.

**Comment by mboitei** [comment]
Merging the PR for RHEL 6.7 compilation error.

**Pull request merged**
